# development:
#   adapter: postgresql
#   encoding: unicode
#   database: ideatap_development
#   pool: 5
#   username: 
#   password:

# test:
#   adapter: postgresql
#   encoding: unicode
#   database: ideatap_test
#   pool: 5
#   username: 
#   password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: ideatap_production
#   pool: 5
#   username:
#   password:
